import { useState } from 'react'
import { AlertTriangle, ArrowLeft, BarChart3, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, CreditCard, GraduationCap, MessageSquareText, Scale, ShieldAlert, TrendingUp, UserPlus, UsersRound, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Metric, PageHeader, StatusBadge } from '../components/ui'
import { can } from '../domain/permissions'
import { buildReport, getOperationalAlerts, PROTOTYPE_TODAY } from '../reporting/selectors'
import { useAppStore } from '../store/useAppStore'
import { currentTeacher, visibleGroups, visibleSessions, visibleStudents } from '../domain/access'
import { buildExecutiveSnapshot } from '../reporting/executive'
import type { ReportingRange } from '../reporting/selectors'

const executiveRanges:Record<string,ReportingRange>={today:{from:'2026-08-11',to:'2026-08-11',label:'اليوم'},week:{from:'2026-08-08',to:'2026-08-14',label:'هذا الأسبوع'},month:{from:'2026-08-01',to:'2026-08-31',label:'هذا الشهر'},previous:{from:'2026-07-01',to:'2026-07-31',label:'الشهر السابق'}}

function ExecutiveDashboard(){
  const state=useAppStore(value=>value),[preset,setPreset]=useState('month'),[from,setFrom]=useState('2026-08-01'),[to,setTo]=useState('2026-08-31'),range=preset==='custom'?{from,to,label:`من ${from} إلى ${to}`}:executiveRanges[preset],snapshot=buildExecutiveSnapshot(state,range)
  return <div className="executive-dashboard">
    <PageHeader eyebrow="الرؤية التنفيذية" title={`صورة الأكاديمية في دقيقتين، ${state.currentUserName}`} description="اتجاهات الأداء والمخاطر والقرارات التي تحتاج رقابة المدير العام، دون تفاصيل التنفيذ اليومي." action={<Link className="button primary" to="/system-summary"><BarChart3/>فتح التقرير التنفيذي</Link>}/>
    <section className="filter-bar executive-range" aria-label="فترة المؤشرات"><label>الفترة<select value={preset} onChange={event=>setPreset(event.target.value)}><option value="today">اليوم</option><option value="week">هذا الأسبوع</option><option value="month">هذا الشهر</option><option value="previous">الشهر السابق</option><option value="custom">نطاق مخصص</option></select></label>{preset==='custom'&&<><label>من<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>إلى<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></>}<span className="range-compare"><TrendingUp/>المقارنة: {snapshot.previous.from} — {snapshot.previous.to}</span></section>
    <section className="executive-kpis" aria-label="المؤشرات التنفيذية">{snapshot.kpis.map(kpi=><Link className={`executive-kpi ${kpi.tone}`} to={kpi.route} key={kpi.id}><div><span>{kpi.label}</span><strong>{kpi.value}</strong></div><StatusBadge tone={kpi.tone==='good'?'success':kpi.tone==='danger'?'danger':kpi.tone==='warning'?'warning':'neutral'}>{kpi.change}</StatusBadge><small>الفترة السابقة: {kpi.previous}</small><span className="kpi-link">عرض المصدر <ArrowLeft/></span></Link>)}</section>
    <div className="grid-two executive-focus-grid"><section className="panel"><div className="section-title"><div><p className="eyebrow danger-text">الأولوية التنفيذية</p><h3>أهم المخاطر الآن</h3></div><Link to="/risks">عرض كل المخاطر</Link></div>{snapshot.risks.slice(0,4).map(risk=><Link className="executive-risk-row" to={risk.route} key={risk.id}><span className={`row-icon ${risk.severity==='حرجة'?'danger':'warning'}`}><ShieldAlert/></span><div><strong>{risk.title}</strong><small>{risk.category} · المسؤول: {risk.owner}</small></div><b>{risk.value}</b><StatusBadge tone={risk.severity==='حرجة'?'danger':'warning'}>{risk.severity}</StatusBadge></Link>)}{!snapshot.risks.length&&<div className="all-clear compact"><CheckCircle2/><strong>لا توجد مخاطر مفتوحة.</strong></div>}</section>
    <section className="panel"><div className="section-title"><div><p className="eyebrow">حوكمة القرار</p><h3>قرارات تنتظر اعتمادك</h3></div><Link to="/decisions">فتح القرارات</Link></div>{snapshot.decisions.slice(0,4).map(decision=><Link className="executive-risk-row" to="/decisions" key={decision.id}><span className="row-icon"><Scale/></span><div><strong>{decision.title}</strong><small>{decision.requestedByName} · {decision.requestedAt}</small></div><StatusBadge tone="warning">بانتظار الاعتماد</StatusBadge></Link>)}{!snapshot.decisions.length&&<div className="all-clear compact"><CheckCircle2/><strong>لا توجد قرارات معلقة.</strong></div>}</section></div>
    <div className="grid-two"><section className="panel"><div className="section-title"><h3>الخلاصة التي تستحق انتباهك</h3></div>{snapshot.insights.map((item,index)=><article className="executive-insight" key={index}><span>{index+1}</span><p>{item}</p></article>)}</section><section className="panel"><div className="section-title"><div><h3>أعمار المتأخرات</h3><p>توزيع التعرض المالي حسب مدة التأخر.</p></div><Link to="/overdue">التفاصيل</Link></div><div className="aging-grid">{snapshot.aging.map(item=><Link to={`/overdue?age=${item.id}`} key={item.id}><span>{item.label}</span><strong>{item.amount.toLocaleString('ar-EG')} ج</strong><small>{item.count} طلاب · {item.share}%</small></Link>)}</div></section></div>
    <section className={`notice ${snapshot.ledgerIssues.length?'danger':'success'}`} role="status"><strong>{snapshot.ledgerIssues.length?'توجد استثناءات تحتاج مراجعة':'تم فحص اتساق دفتر الحركات'}</strong><p>{snapshot.ledgerIssues[0]||'كل أرصدة الطلاب تطابق الحركات المالية الموثقة.'}</p>{snapshot.ledgerIssues.length>0&&<Link className="text-link" to="/ledger?filter=issues">فتح فحص الاتساق</Link>}</section>
  </div>
}

function TeacherDashboard(){const state=useAppStore(value=>value),context={role:state.role,currentTeacherId:state.currentTeacherId,teachers:state.teachers,groups:state.groups,sessions:state.sessions,students:state.students},teacher=currentTeacher(context),groups=visibleGroups(context),sessions=visibleSessions(context),students=visibleStudents(context),today=sessions.filter(item=>item.date===PROTOTYPE_TODAY),missing=today.filter(item=>!state.attendance.some(row=>row.sessionId===item.id));return <><PageHeader eyebrow="مساحة المدرس" title={`يومك الدراسي${teacher?`، ${teacher.name}`:''}`} description="حصصك ومجموعاتك وطلابك فقط؛ لا تظهر هنا البيانات الإدارية أو المالية."/><section className="metrics dashboard-metrics"><Metric label="حصصي اليوم" value={today.length}/><Metric label="مجموعاتي" value={groups.length}/><Metric label="طلابي" value={students.length}/><Metric label="حضور ينتظر التسجيل" value={missing.length}/></section><div className="grid-two"><section className="panel"><div className="section-title"><div><p className="eyebrow">اليوم</p><h3>حصصي المجدولة</h3></div><Link to="/calendar">فتح جدولي <ArrowLeft/></Link></div>{today.map(session=><Link className="session-operation-row" key={session.id} to={`/sessions/${session.id}`}><span className="row-icon"><CalendarDays/></span><div><strong>{session.group}</strong><small>{session.room} · {session.start}–{session.end}</small></div><StatusBadge tone={state.attendance.some(row=>row.sessionId===session.id)?'success':'warning'}>{state.attendance.some(row=>row.sessionId===session.id)?'تم الحضور':'ينتظر الحضور'}</StatusBadge></Link>)}{!today.length&&<div className="all-clear compact"><CheckCircle2/><strong>لا توجد حصص لك اليوم.</strong></div>}</section><section className="panel"><div className="section-title"><div><p className="eyebrow">نطاق حسابك</p><h3>مجموعاتي وطلابي</h3></div><Link to="/students">عرض طلابي</Link></div>{groups.map(group=><Link className="list-row" key={group.id} to={`/groups/${group.id}`}><span className="row-icon"><UsersRound/></span><div><strong>{group.name}</strong><small>{group.schedule} · {group.room}</small></div><b>{students.filter(item=>item.group===group.name).length} طالب</b></Link>)}{!groups.length&&<EmptyTeacherState/>}</section></div></>}

function EmptyTeacherState(){return <div className="all-clear compact"><CheckCircle2/><div><strong>لا توجد مجموعة مسندة لهذا الحساب.</strong><p>راجع مدير التشغيل لإتمام الإسناد.</p></div></div>}

function FollowupDashboard(){const students=useAppStore(state=>state.students),followups=useAppStore(state=>state.followups),attendance=useAppStore(state=>state.attendance),sessions=useAppStore(state=>state.sessions),overdue=students.filter(item=>item.paid<item.total),escalated=new Set(followups.filter(item=>item.escalated).map(item=>item.studentId)),missing=sessions.filter(item=>item.date===PROTOTYPE_TODAY&&!attendance.some(row=>row.sessionId===item.id));return <><PageHeader eyebrow="مساحة المتابعة" title="مركز متابعة الطلاب" description="حالات التواصل والتصعيد والحضور التي تحتاج تدخل موظف المتابعة، دون صلاحيات مالية أو إدارية."/><section className="metrics dashboard-metrics"><Metric label="حالات سداد للمتابعة" value={overdue.length}/><Metric label="حالات مصعّدة" value={escalated.size}/><Metric label="متابعات مسجلة" value={followups.length}/><Metric label="حضور غير مكتمل اليوم" value={missing.length}/></section><section className="quick-actions"><div className="section-title"><h3>مهامي السريعة</h3></div><div><Link to="/overdue"><AlertTriangle/><span>متابعة المتأخرات</span></Link><Link to="/messages"><MessageSquareText/><span>تجهيز رسالة</span></Link><Link to="/students"><UsersRound/><span>ملفات المتابعة</span></Link><Link to="/attendance"><CalendarDays/><span>حالة الحضور</span></Link></div></section><section className="panel"><div className="section-title"><div><p className="eyebrow danger-text">الأولوية الآن</p><h3>الحالات المصعّدة</h3></div><Link to="/overdue">عرض الكل</Link></div>{overdue.filter(item=>escalated.has(item.id)).map(item=><Link className="list-row" key={item.id} to={`/overdue/${item.id}`}><span className="row-icon warning"><AlertTriangle/></span><div><strong>{item.name}</strong><small>{item.phone} · {item.due}</small></div><b>{item.total-item.paid} ج</b></Link>)}{!escalated.size&&<div className="all-clear compact"><CheckCircle2/><strong>لا توجد حالات مصعّدة.</strong></div>}</section></>}

function AccountantDashboard(){const students=useAppStore(state=>state.students),payments=useAppStore(state=>state.payments),pending=payments.filter(item=>item.status==='بانتظار المراجعة'),outstanding=students.reduce((sum,item)=>sum+item.total-item.paid,0),collected=students.reduce((sum,item)=>sum+item.paid,0);return <><PageHeader eyebrow="المساحة المالية" title="مركز المدفوعات" description="الأرصدة وطلبات الدفع والمراجعة فقط؛ لا تظهر بيانات الحضور أو الجداول أو الإدارة."/><section className="metrics dashboard-metrics"><Metric label="قيد المراجعة" value={pending.length}/><Metric label="قيمة قيد المراجعة" value={`${pending.reduce((sum,item)=>sum+item.amount,0)} ج`}/><Metric label="إجمالي المحصل" value={`${collected.toLocaleString('ar-EG')} ج`}/><Metric label="الرصيد المستحق" value={`${outstanding.toLocaleString('ar-EG')} ج`}/></section><section className="quick-actions"><div className="section-title"><h3>الإجراءات المالية</h3></div><div><Link to="/payments/new"><CreditCard/><span>تسجيل دفعة</span></Link><Link to="/payments/review"><WalletCards/><span>مراجعة الدفعات</span></Link><Link to="/payments"><CircleDollarSign/><span>سجل المدفوعات</span></Link><Link to="/students"><UsersRound/><span>أرصدة الطلاب</span></Link></div></section><section className="panel"><div className="section-title"><div><p className="eyebrow">طابور المراجعة</p><h3>دفعات تنتظر قرارك</h3></div><Link to="/payments/review">فتح الطابور</Link></div>{pending.map(item=>{const student=students.find(row=>row.id===item.studentId);return <Link className="list-row" key={item.id} to={`/payments/review/${item.id}`}><span className="row-icon warning"><WalletCards/></span><div><strong>{student?.name}</strong><small>{item.id} · {item.reference}</small></div><b>{item.amount} ج</b></Link>})}{!pending.length&&<div className="all-clear compact"><CheckCircle2/><strong>تمت مراجعة كل الدفعات.</strong></div>}</section></>}

export function DashboardPage(){
  const students=useAppStore(s=>s.students),teachers=useAppStore(s=>s.teachers),groups=useAppStore(s=>s.groups),sessions=useAppStore(s=>s.sessions),attendance=useAppStore(s=>s.attendance),payments=useAppStore(s=>s.payments),followups=useAppStore(s=>s.followups),audit=useAppStore(s=>s.audit),role=useAppStore(s=>s.role)
  const source={students,teachers,groups,sessions,attendance,payments,followups,audit},report=buildReport(source,{from:PROTOTYPE_TODAY,to:PROTOTYPE_TODAY,label:'اليوم'}),alerts=getOperationalAlerts(source),today=report.sessions,attendancePercent=today.length?Math.round(report.sessionMetrics.attendanceComplete/today.length*100):0
  const quick=[
    ['student.create','/students/new','إضافة طالب',UserPlus],['teacher.create','/teachers/new','إضافة مدرس',GraduationCap],['group.assign','/groups','إدارة مجموعة',UsersRound],['teacher.schedule','/calendar','إضافة حصة',CalendarDays],['payment.create','/payments/new','تسجيل دفعة',CreditCard],['schedule.view','/calendar','فتح الجدول الأسبوعي',Clock3],
  ] as const
  if(role==='المدير العام')return <ExecutiveDashboard/>
  if(role==='المدرس')return <TeacherDashboard/>
  if(role==='موظف المتابعة')return <FollowupDashboard/>
  if(role==='المحاسب')return <AccountantDashboard/>
  return <>
    <PageHeader eyebrow="إدارة عمليات اليوم" title="ملخص تشغيل الأكاديمية اليوم" description="تابع سير العمل والحصص والحضور والمدفوعات والحالات التي تحتاج إلى تدخلك."/>
    <section className="attention-section" aria-labelledby="attention-title"><div className="section-heading"><div><p className="eyebrow danger-text">الأولوية الآن</p><h3 id="attention-title">يحتاج إلى تدخلك</h3><p>الحالات التي تتطلب مراجعة أو إجراءً من مدير التشغيل.</p></div><span className="attention-count">{alerts.length} حالات</span></div>{alerts.length?<div className="attention-grid">{alerts.map(alert=><article className={`attention-card ${alert.tone}`} key={alert.id}><span className="attention-icon"><AlertTriangle/></span><div><strong>{alert.title}</strong><p>{alert.description}</p><small>{alert.count.toLocaleString('ar-EG')} {alert.count===1?'حالة':'حالات'}</small></div><Link className="button secondary" to={alert.route}>{alert.action}<ArrowLeft/></Link></article>)}</div>:<div className="all-clear"><CheckCircle2/><div><strong>لا توجد حالات عاجلة حاليًا.</strong><p>يسير التشغيل بصورة طبيعية ولا توجد حالات تتطلب تدخلك الآن.</p></div></div>}</section>
    <section className="dashboard-section"><div className="section-heading"><div><p className="eyebrow">ملخص اليوم</p><h3>المؤشرات التشغيلية الأساسية</h3></div></div><div className="metrics dashboard-metrics">
      <Metric label="الحصص المجدولة اليوم" value={today.length} hint={`${today.filter(s=>s.status==='قادمة'||s.status==='اليوم').length} قادمة · ${today.filter(s=>s.status==='مكتملة').length} مكتملة`}/>
      <Metric label="اكتمال تسجيل الحضور" value={`${report.sessionMetrics.attendanceComplete} من ${today.length}`} hint={`${report.sessionMetrics.attendanceMissing} حصص تنتظر التسجيل`}/>
      <Metric label="الطلاب المسجلون حاليًا" value={report.students.active} hint="لديهم ملف فعّال في الأكاديمية"/>
      <Metric label="المجموعات الدراسية الحالية" value={groups.filter(g=>g.status==='نشطة'||g.status==='مكتملة').length} hint={`${report.groups.near+report.groups.full} تحتاج متابعة السعة`}/>
      <Metric label="المدرسون الذين لديهم حصص اليوم" value={report.teacherMetrics.working} hint="حسب الجدول الحالي"/>
      <Metric label="حالات السداد التي تحتاج متابعة" value={report.finance.overdueStudents} hint={`${report.finance.escalated} حالات مصعّدة`}/>
    </div></section>
    <section className="quick-actions" aria-label="إجراءات سريعة"><div className="section-title"><div><p className="eyebrow">اختصارات الإدارة</p><h3>إجراءات سريعة</h3></div></div><div>{quick.filter(([permission])=>can(role,permission)).map(([permission,to,label,Icon])=><Link key={permission} to={to}><Icon/><span>{label}</span></Link>)}</div></section>
    <div className="grid-two dashboard-primary-grid">
      <section className="panel"><div className="section-title"><div><p className="eyebrow">اليوم</p><h3>الحصص المجدولة اليوم</h3><p>الحصص المقرر عقدها اليوم وفق الجدول الحالي.</p></div><Link to="/calendar">عرض التقويم <ArrowLeft/></Link></div>{today.map(session=>{const hasAttendance=attendance.some(a=>a.sessionId===session.id);return <Link className="session-operation-row" key={session.id} to={`/sessions/${session.id}`}><span className="row-icon"><CalendarDays/></span><div><strong>{session.group}</strong><small>المدرس: {session.instructor} · القاعة: {session.room}</small></div><div><b>{session.start}</b><small>الوقت</small></div><div className="session-statuses"><StatusBadge tone={session.status==='مكتملة'?'success':'neutral'}>الحصة {session.status}</StatusBadge><StatusBadge tone={hasAttendance?'success':'warning'}>{hasAttendance?'تم تسجيل الحضور':'لم يُسجّل الحضور'}</StatusBadge></div></Link>})}{!today.length&&<div className="all-clear compact"><CheckCircle2/><div><strong>لا توجد حصص مجدولة اليوم.</strong></div></div>}</section>
      <section className="panel attendance-control"><div className="section-title"><div><p className="eyebrow">الرقابة اليومية</p><h3>متابعة تسجيل الحضور</h3><p>راقب اكتمال عمل الحضور دون الدخول في سجلات الطلاب.</p></div></div><div className="progress-summary"><strong>{attendancePercent}%</strong><div><span>تم تسجيل الحضور لـ {report.sessionMetrics.attendanceComplete} من أصل {today.length} حصة</span><progress className="progress-native" value={attendancePercent} max="100">{attendancePercent}%</progress></div></div>{report.missingAttendance.slice(0,3).map(s=><Link className="list-row" key={s.id} to={`/attendance/${s.id}`}><span className="row-icon warning"><Clock3/></span><div><strong>{s.group}</strong><small>{s.start} · {s.instructor}</small></div><StatusBadge tone="warning">ينتظر التسجيل</StatusBadge></Link>)}<Link className="button secondary full-button" to="/attendance">عرض الحصص التي لم يُسجّل حضورها</Link></section>
    </div>
    <div className="grid-two">
      <section className="panel"><div className="section-title"><div><p className="eyebrow danger-text">متابعة السداد</p><h3>حالات السداد التي تحتاج متابعة</h3><p>طلاب لديهم مبالغ تجاوزت موعد الاستحقاق وتحتاج إلى متابعة.</p></div><Link to="/overdue">عرض جميع حالات السداد</Link></div>{report.overdue.slice(0,5).map(student=>{const records=followups.filter(f=>f.studentId===student.id),escalated=records.some(f=>f.escalated);return <Link className="list-row overdue-row" key={student.id} to={`/overdue/${student.id}`}><span className="row-icon warning"><AlertTriangle/></span><div><strong>{student.name}</strong><small>المجموعة: {student.group||'غير مسند'} · متأخر {student.due}</small><small>آخر متابعة: {records[0]?.result||'لم تبدأ المتابعة'}</small></div><b>{(student.total-student.paid).toLocaleString('ar-EG')} ج</b>{escalated&&<StatusBadge tone="danger">مصعّدة</StatusBadge>}</Link>})}</section>
      <section className="panel"><div className="section-title"><div><p className="eyebrow">الطاقة الاستيعابية</p><h3>المجموعات التي تحتاج انتباهًا</h3><p>المجموعات المكتملة أو القريبة من اكتمال السعة.</p></div><Link to="/groups">عرض جميع المجموعات</Link></div>{[...report.fullGroups,...report.nearGroups].map(group=>{const percent=Math.round(group.enrolled/group.capacity*100);return <Link className="capacity-row" key={group.id} to={`/groups/${group.id}`}><div><strong>{group.name}</strong><small>{group.instructor} · {group.room}</small></div><div><b>{group.enrolled} / {group.capacity} طالبًا</b><progress className="progress-native" value={percent} max="100">{percent}%</progress><small>{group.enrolled>=group.capacity?'المجموعة مكتملة':`تبقى ${group.capacity-group.enrolled} مقعد`}</small></div></Link>})}</section>
    </div>
    <div className="grid-two">
      <section className="panel payment-oversight"><div className="section-title"><div><p className="eyebrow">الرقابة المالية</p><h3>حالة مراجعة المدفوعات</h3></div><Link to="/payments/review">فتح مراجعة المدفوعات</Link></div><div className="mini-metrics"><div><span>تنتظر المراجعة</span><strong>{payments.filter(item=>item.status==='بانتظار المراجعة').length}</strong></div><div><span>معتمدة اليوم</span><strong>{report.paymentMetrics.approved}</strong></div><div><span>مرفوضة اليوم</span><strong>{report.paymentMetrics.rejected}</strong></div></div>{!payments.some(item=>item.status==='بانتظار المراجعة')&&<p className="notice success">تمت مراجعة جميع الدفعات المسجلة.</p>}</section>
      <section className="panel"><div className="section-title"><div><p className="eyebrow">آخر التغييرات</p><h3>آخر العمليات المهمة</h3></div><Link to="/audit">عرض سجل النشاط بالكامل</Link></div>{audit.slice(0,5).map(item=><article className="activity-compact" key={item.id}><span>{item.type}</span><div><strong>{item.title}</strong><p>{item.detail}</p><small>بواسطة: {item.user} · {item.at}</small></div></article>)}</section>
    </div>
    <section className="operations-banner"><span><CircleDollarSign/></span><div><strong>إجمالي المبالغ المستحقة على الطلاب</strong><p>مجموع المبالغ التي لم يتم تحصيلها حتى الآن، سواء حل موعدها أم لا.</p></div><b>{report.finance.outstanding.toLocaleString('ar-EG')} ج</b></section>
  </>
}
