import { useDeferredValue, useState, type FormEvent } from 'react'
import { AlertTriangle, Archive, Plus, RotateCcw, Search, Trash2, Users } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ConfirmDialog, PageHeader, ProtectedButton, StatusBadge, EmptyState, Metric } from '../components/ui'
import type { BusinessResult } from '../domain/types'
import { can } from '../domain/permissions'
import { visibleGroups, visibleStudents } from '../domain/access'
import { normalizePhone } from '../domain/validation'
import { useAppStore } from '../store/useAppStore'

export function RecordActions({name,archived,onArchive,onDelete,deleteImpact,onDeleted}:{name:string;archived:boolean;onArchive:(archived:boolean)=>BusinessResult;onDelete:()=>BusinessResult;deleteImpact:string;onDeleted:()=>void}){
  const[action,setAction]=useState<'archive'|'delete'|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('')
  const run=(operation:()=>BusinessResult,deleted=false)=>{const result=operation();if(!result.ok){setError(result.message);return}setError('');setMessage(deleted?'تم حذف السجل المحلي نهائيًا.':archived?'تمت استعادة السجل.':'تمت أرشفة السجل.');if(deleted)onDeleted()}
  return <div className="record-actions">{error&&<span className="field-error" role="alert">{error}</span>}{message&&<span className="success-text" role="status" aria-live="polite">{message}</span>}<button className="button secondary" onClick={()=>setAction('archive')}>{archived?<RotateCcw/>:<Archive/>}{archived?'استعادة':'أرشفة'}</button><button className="button danger" onClick={()=>setAction('delete')}><Trash2/>حذف نهائي</button><ConfirmDialog open={action==='archive'} title={`${archived?'استعادة':'أرشفة'} ${name}`} description={archived?'سيعود السجل إلى القوائم النشطة ويمكن استخدامه مجددًا.':'سيختفي السجل من القوائم النشطة مع الاحتفاظ بتاريخه المحلي.'} impact="يُسجل الإجراء في سجل النشاط ويمكن عكس الأرشفة لاحقًا." confirmLabel={archived?'استعادة السجل':'أرشفة السجل'} onClose={()=>setAction(null)} onConfirm={()=>run(()=>onArchive(!archived))}/><ConfirmDialog open={action==='delete'} title={`حذف ${name} نهائيًا`} description="هذا حذف محلي نهائي داخل النسخة التجريبية، ويختلف عن الأرشفة القابلة للاستعادة." impact={deleteImpact} confirmLabel="تأكيد الحذف النهائي" danger onClose={()=>setAction(null)} onConfirm={()=>run(onDelete,true)}/></div>
}

export function StudentsPage() {
  const state=useAppStore(value=>value),role=state.role,students=visibleStudents({role,currentTeacherId:state.currentTeacherId,teachers:state.teachers,groups:state.groups,sessions:state.sessions,students:state.students}),location=useLocation()
  const initialAssignment=new URLSearchParams(location.search).get('assignment')||''
  const [query, setQuery] = useState(''),[assignment,setAssignment]=useState(initialAssignment)
  const deferredQuery=useDeferredValue(query)
  const rows = students.filter(student => `${student.name} ${student.phone} ${student.code}`.includes(deferredQuery)&&(!assignment||(assignment==='unassigned'?!student.group:Boolean(student.group))))
  const canAdd = can(role, 'student.create')
  return <>
    <PageHeader eyebrow={role==='المدرس'?'مساحتي التعليمية':'إدارة الطلاب'} title={role==='المدرس'?'طلابي':'الطلاب'} description={role==='المدرس'?'الطلاب المسندون إلى مجموعاتك فقط، دون بيانات مالية أو متابعات إدارية.':role==='المحاسب'?'بيانات السداد الخاصة بالطلاب دون سجلات الحضور أو المتابعة.':role==='موظف المتابعة'?'بيانات التواصل والمتابعة المطلوبة دون صلاحيات التعديل الإداري.':'بحث موحّد وملفات كاملة للحضور والدفعات والمتابعة.'} action={canAdd ? <Link className="button primary" to="/students/new"><Plus />إضافة طالب</Link> : undefined} />
    <section className="panel"><div className="student-filters"><label className="search-field" htmlFor="student-search"><Search /><span className="sr-only">بحث عن طالب</span><input id="student-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="الاسم أو الهاتف أو كود الطالب" /></label><label className="field compact-field"><span>إسناد المجموعة</span><select value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">كل الطلاب</option><option value="unassigned">غير مسندين إلى مجموعة</option><option value="assigned">مسندون إلى مجموعة</option></select></label></div><div className="table-wrap responsive-table"><table><caption className="sr-only">قائمة الطلاب</caption><thead><tr><th>الطالب</th><th>المجموعة</th>{role==='المدرس'?<><th>الدورة</th><th>الحضور</th></>:role==='موظف المتابعة'?<><th>الرصيد</th><th>المتابعة</th></>:<><th>السداد</th><th>الحالة</th></>}<th>الإجراء</th></tr></thead><tbody>{rows.map(student=>{const records=state.attendance.filter(item=>item.studentId===student.id),followup=state.followups.find(item=>item.studentId===student.id);return <tr key={student.id}><td data-label="الطالب"><strong>{student.name}</strong><small>{student.code}{role!=='المدرس'&&` · ${student.phone}`}</small></td><td data-label="المجموعة">{student.group||<StatusBadge tone="warning">ينتظر الإلحاق</StatusBadge>}</td>{role==='المدرس'?<><td data-label="الدورة">{student.course}</td><td data-label="الحضور">{records.length?`${records.filter(item=>item.status==='حاضر').length} من ${records.length}`:'لا يوجد سجل'}</td></>:role==='موظف المتابعة'?<><td data-label="الرصيد">{student.total-student.paid} ج</td><td data-label="المتابعة">{followup?.result||'لم تبدأ'}</td></>:<><td data-label="السداد">{student.paid.toLocaleString('ar-EG')} / {student.total.toLocaleString('ar-EG')} ج</td><td data-label="الحالة"><StatusBadge tone={student.paid===student.total?'success':'warning'}>{student.paid===student.total?'مستوفى':'متبقي'}</StatusBadge></td></>}<td data-label="الإجراء"><Link className="text-link" to={`/students/${student.id}`}>فتح الملف</Link></td></tr>})}</tbody></table></div>{!rows.length && <EmptyState title="لا توجد نتائج مطابقة" description="غيّر كلمات البحث وحاول مجددًا." />}</section>
  </>
}

export function NewStudentPage() {
  const students = useAppStore(state => state.students), groups = useAppStore(state => state.groups), addStudent = useAppStore(state => state.addStudent)
  const navigate = useNavigate()
  const [phone, setPhone] = useState(''), [step, setStep] = useState(1), [error, setError] = useState('')
  const normalizedPhone = normalizePhone(phone)
  const existing = students.find(student => normalizePhone(student.phone) === normalizedPhone && normalizedPhone.length > 0)
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('')
    const data = new FormData(event.currentTarget)
    const result = addStudent({ name: String(data.get('name')).trim(), phone: normalizedPhone, guardian: String(data.get('guardian')), group: String(data.get('group')), course: String(data.get('course')), packageName: String(data.get('packageName')), paid: 0, total: 1200, due: 'بانتظار السداد' })
    if (!result.ok) { setError(result.message); return }
    navigate(`/students/${result.value.id}`)
  }
  return <>
    <PageHeader eyebrow="الطلاب / إضافة" title="تسجيل طالب جديد" description="فحص التكرار أولًا، ثم يمكن إسناد المجموعة الآن أو لاحقًا." />
    <section className="flow-card"><div className="steps" aria-label="خطوات التسجيل"><span className="active">1. فحص الهاتف</span><span className={step === 2 ? 'active' : ''}>2. البيانات والمجموعة</span></div>{step === 1 ? <>
      <label className="field"><span>رقم الهاتف الأساسي</span><input autoFocus type="tel" value={phone} onChange={event => { setPhone(event.target.value); setError('') }} placeholder="01xxxxxxxxx" /></label>
      {existing && <div className="duplicate-warning" role="alert"><span><AlertTriangle /></span><div><strong>لا يمكن إنشاء طالب مكرر</strong><p>رقم الهاتف مسجل بالفعل في ملف الطالب التالي:</p><dl><div><dt>الاسم</dt><dd>{existing.name}</dd></div><div><dt>الهاتف</dt><dd>{existing.phone}</dd></div><div><dt>المجموعة</dt><dd>{existing.group}</dd></div><div><dt>الاشتراك</dt><dd>{existing.paid === existing.total ? 'مستوفى' : `متبقي ${existing.total - existing.paid} ج`}</dd></div></dl><Link className="button secondary" to={`/students/${existing.id}`}>فتح ملف الطالب الحالي</Link></div></div>}
      {error && <p className="field-error" role="alert">{error}</p>}
      <div className="form-actions"><button className="button secondary" onClick={() => navigate('/students')}>إلغاء</button><button className="button primary" disabled={normalizedPhone.length < 10 || Boolean(existing)} onClick={() => setStep(2)}>متابعة</button></div>
    </> : <form onSubmit={submit}><div className="notice neutral"><strong>الهاتف بعد التحقق: {normalizedPhone}</strong></div><div className="form-grid"><label className="field"><span>الاسم الكامل</span><input required name="name" /></label><label className="field"><span>هاتف ولي الأمر</span><input name="guardian" type="tel" /></label><label className="field"><span>الدورة</span><select name="course"><option>اللغة العربية</option><option>الرياضيات</option></select></label><label className="field"><span>الباقة</span><select name="packageName"><option>شهرية · 8 حصص</option><option>شهرية · 12 حصة</option></select></label><label className="field full"><span>المجموعة</span><select name="group" defaultValue=""><option value="">إسناد المجموعة لاحقًا</option>{groups.map(group => { const full = group.enrolled >= group.capacity; return <option key={group.id} value={group.name} disabled={full}>{group.name} · {group.enrolled}/{group.capacity}{full ? ' · مكتملة' : ''}</option> })}</select><small>إذا تركتها دون مجموعة فسيظهر الطالب ضمن حالات الإلحاق المطلوبة.</small></label></div>{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => setStep(1)}>رجوع</button><ProtectedButton permission="student.create" className="button primary">تأكيد وإضافة الطالب</ProtectedButton></div></form>}</section>
  </>
}

export function StudentProfilePage() {
  const { id } = useParams(),navigate=useNavigate()
  const role=useAppStore(state=>state.role),student = useAppStore(state => state.students.find(item => item.id === id)), allPayments = useAppStore(state => state.payments), allAttendance = useAppStore(state => state.attendance), allFollowups = useAppStore(state => state.followups),archiveStudent=useAppStore(state=>state.archiveStudent),deleteStudent=useAppStore(state=>state.deleteStudent)
  const payments = allPayments.filter(item => item.studentId === id && item.status === 'معتمدة'), attendance = allAttendance.filter(item => item.studentId === id), followups = allFollowups.filter(item => item.studentId === id)
  const [tab, setTab] = useState<'overview' | 'payments' | 'attendance' | 'followups'>('overview')
  if (!student) return <EmptyState title="الطالب غير موجود" />
  const tabs = ([['overview', 'نظرة عامة'],...(role==='مدير التشغيل'||role==='المحاسب'?[['payments', `الدفعات (${payments.length})`]]:[]),...(role==='مدير التشغيل'||role==='المدرس'||role==='موظف المتابعة'?[['attendance', `الحضور (${attendance.length})`]]:[]),...(role==='مدير التشغيل'||role==='موظف المتابعة'?[['followups', `المتابعة (${followups.length})`]]:[])]) as [typeof tab,string][]
  const overviewFields=role==='المدرس'?[['الدورة',student.course],['المجموعة',student.group],['الباقة',student.packageName],['حالة الملف',student.status]]:role==='المحاسب'?[['المجموعة',student.group],['الباقة',student.packageName],['حالة الحساب',student.status],['الاستحقاق',student.due]]:[['الدورة',student.course],['المجموعة',student.group],['الباقة',student.packageName],['هاتف ولي الأمر',student.guardian],['حالة الحساب',student.status],['الاستحقاق',student.due]]
  return <>
    <section className="profile-hero"><div className="avatar">{student.name[0]}</div><div className="truncate-safe"><p>{student.code}</p><h2>{student.name}</h2><small>{student.phone} · {student.group||'غير مسند إلى مجموعة'}</small></div>{can(role,'student.update')&&<div className="profile-edit"><Link className="button secondary" to={`/students/${student.id}/edit`}>تعديل الملف</Link><RecordActions name={`الطالب ${student.name}`} archived={student.status==='مؤرشف'} onArchive={value=>archiveStudent(student.id,value)} onDelete={()=>deleteStudent(student.id)} deleteImpact={`سيتم حذف الحضور والمتابعات والدفعات المحلية المرتبطة، وتحديث إشغال مجموعة ${student.group||'غير مسند'}.`} onDeleted={()=>navigate('/students')}/></div>}{role!=='المدرس'&&<StatusBadge tone={student.status==='مؤرشف'?'neutral':student.paid === student.total ? 'success' : 'warning'}>{student.status==='مؤرشف'?'مؤرشف':student.paid === student.total ? 'مستوفى' : 'رصيد مستحق'}</StatusBadge>}</section>
    <section className="metrics profile-metrics">{role==='المدرس'?<><Metric label="المجموعة" value={student.group||'—'} /><Metric label="الدورة" value={student.course}/><Metric label="سجلات الحضور" value={attendance.length}/><Metric label="نسبة الحضور" value={attendance.length ? `${Math.round(attendance.filter(row => row.status === 'حاضر').length / attendance.length * 100)}%` : '—'} /></>:role==='موظف المتابعة'?<><Metric label="الرصيد المتبقي" value={`${student.total-student.paid} ج`}/><Metric label="الاستحقاق" value={student.due}/><Metric label="محاولات التواصل" value={followups.length}/><Metric label="التصعيد" value={followups.some(item=>item.escalated)?'مصعّدة':'عادية'}/></>:<><Metric label="إجمالي الاشتراك" value={`${student.total} ج`} /><Metric label="المدفوع" value={`${student.paid} ج`} /><Metric label="المتبقي" value={`${student.total - student.paid} ج`} /><Metric label="الحضور" value={role==='المحاسب'?'غير متاح':attendance.length ? `${Math.round(attendance.filter(row => row.status === 'حاضر').length / attendance.length * 100)}%` : '—'} /></>}</section>
    <nav className="tabs" aria-label="أقسام ملف الطالب">{tabs.map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}</nav>
    <section className="panel">{tab === 'overview' && <div className="info-grid">{overviewFields.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}{tab === 'payments' && (payments.length ? payments.map(item => <article className="timeline-item" key={item.id}><strong>{item.amount} ج · {item.method}</strong><p>{item.paymentDate} · {item.reference}</p><StatusBadge tone="success">{item.status}</StatusBadge></article>) : <EmptyState title="لا توجد دفعات معتمدة" />)}{tab === 'attendance' && (attendance.length ? attendance.map(item => <article className="timeline-item" key={item.id}><strong>{item.date} · {item.group}</strong><p>{item.note || 'دون ملاحظة'}</p><StatusBadge tone={item.status === 'حاضر' ? 'success' : item.status === 'متأخر' ? 'warning' : 'danger'}>{item.status}</StatusBadge></article>) : <EmptyState title="لا توجد سجلات حضور" />)}{tab === 'followups' && (followups.length ? followups.map(item => <article className="timeline-item" key={item.id}><strong>{item.method} · {item.result}</strong><p>{item.date} · {item.note}</p>{item.escalated && <StatusBadge tone="danger">مصعّدة</StatusBadge>}</article>) : <EmptyState title="لا توجد متابعات" />)}</section>
  </>
}

export function GroupsPage() {
  const state=useAppStore(value=>value),groups=visibleGroups({role:state.role,currentTeacherId:state.currentTeacherId,teachers:state.teachers,groups:state.groups,sessions:state.sessions,students:state.students})
  return <><PageHeader eyebrow="التشغيل" title={state.role==='المدرس'?'مجموعاتي':'المجموعات'} description={state.role==='المدرس'?'المجموعات المسندة إلى حسابك فقط.':'الإشغال والمدرس والقاعة والجدول في عرض واحد.'} action={can(state.role,'group.assign')?<Link className="button primary" to="/groups/new"><Plus/>إضافة مجموعة</Link>:undefined}/><section className="card-grid">{groups.map(group => { const full = group.enrolled >= group.capacity,archived=group.status==='مؤرشفة',percent=Math.min(100,group.enrolled/group.capacity*100); return <Link className={`group-card ${full ? 'full' : ''}`} to={`/groups/${group.id}`} key={group.id}><div><h3>{group.name}</h3><StatusBadge tone={archived?'neutral':full ? 'danger' : 'success'}>{archived?'مؤرشفة':full ? 'مكتملة السعة' : 'متاحة'}</StatusBadge></div><p>{group.course}</p><dl><div><dt>المدرس</dt><dd>{group.instructor}</dd></div><div><dt>القاعة</dt><dd>{group.room}</dd></div><div><dt>الجدول</dt><dd>{group.schedule}</dd></div></dl><progress className="progress-native" value={percent} max="100">{Math.round(percent)}%</progress><small>{group.enrolled} من {group.capacity} طالب{full ? ' · لا توجد مقاعد متاحة' : ''}</small></Link> })}</section>{!groups.length&&<EmptyState title="لا توجد مجموعات" description="أنشئ المجموعة الأولى ثم أضف الطلاب وجدول الحصص." action={can(state.role,'group.assign')?<Link className="button primary" to="/groups/new">إضافة مجموعة</Link>:undefined}/>}</>
}

export function NewGroupPage(){const add=useAppStore(state=>state.addGroup),allTeachers=useAppStore(state=>state.teachers),teachers=allTeachers.filter(item=>item.status==='نشط'),navigate=useNavigate();const[error,setError]=useState('');const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),result=add({name:String(data.get('name')),course:String(data.get('course')),instructor:String(data.get('instructor')),room:String(data.get('room')),capacity:Number(data.get('capacity')),schedule:String(data.get('schedule'))});if(!result.ok){setError(result.message);return}navigate(`/groups/${result.value.id}`)};return <><PageHeader eyebrow="المجموعات / إضافة" title="إنشاء مجموعة جديدة" description="أدخل السعة والجدول والمدرس؛ يبدأ الإشغال بصفر ويتحدث تلقائيًا عند إلحاق الطلاب."/><form className="flow-card" onSubmit={submit}><div className="form-grid"><label className="field full"><span>اسم المجموعة</span><input name="name" required maxLength={80}/></label><label className="field"><span>الدورة أو المستوى</span><input name="course" required/></label><label className="field"><span>المدرس</span><select name="instructor" required>{teachers.map(item=><option key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>القاعة</span><select name="room">{['قاعة 1','قاعة 2','قاعة 3','قاعة 4','قاعة 5'].map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><span>السعة</span><input name="capacity" type="number" min="1" max="100" defaultValue="15" required/></label><label className="field full"><span>الجدول</span><input name="schedule" placeholder="الأحد والثلاثاء · 5:00 م" required/></label></div>{error&&<p className="field-error" role="alert">{error}</p>}<div className="form-actions"><Link className="button secondary" to="/groups">إلغاء</Link><ProtectedButton permission="group.assign" className="button primary">إنشاء المجموعة</ProtectedButton></div></form></>}

export function StudentEditPage() {
  const { id } = useParams(), navigate = useNavigate()
  const student = useAppStore(state => state.students.find(item => item.id === id)), groups = useAppStore(state => state.groups), update = useAppStore(state => state.updateStudent)
  const [error, setError] = useState('')
  if (!student) return <EmptyState title="الطالب غير موجود" />
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('')
    const data = new FormData(event.currentTarget)
    const result = update(student.id, { name: String(data.get('name')), phone: String(data.get('phone')), guardian: String(data.get('guardian')), group: String(data.get('group')), course: String(data.get('course')), packageName: String(data.get('packageName')), status: String(data.get('status')) as 'نشط' | 'موقوف' })
    if (!result.ok) { setError(result.message); return }
    navigate(`/students/${student.id}`)
  }
  return <><PageHeader eyebrow="الطلاب / تعديل" title={`تعديل ملف ${student.name}`} description="تُحفظ التغييرات محليًا ويُسجل المستخدم والوقت في سجل النشاط." /><form className="flow-card" onSubmit={submit}><div className="form-grid"><label className="field full"><span>الاسم</span><input name="name" defaultValue={student.name} required /></label><label className="field"><span>الهاتف</span><input name="phone" defaultValue={student.phone} required /></label><label className="field"><span>هاتف ولي الأمر</span><input name="guardian" defaultValue={student.guardian} /></label><label className="field"><span>الدورة</span><select name="course" defaultValue={student.course}><option>اللغة العربية</option><option>الرياضيات</option></select></label><label className="field"><span>المجموعة</span><select name="group" defaultValue={student.group}><option value="">غير مسند إلى مجموعة</option>{groups.map(item => { const full = item.enrolled >= item.capacity && item.name !== student.group; return <option key={item.id} value={item.name} disabled={full}>{item.name} · {item.enrolled}/{item.capacity}{full ? ' · مكتملة' : ''}</option> })}</select><small>يمكن إلحاق الطالب بمجموعة متاحة أو إبقاؤه ضمن قائمة انتظار الإلحاق.</small></label><label className="field"><span>الباقة</span><select name="packageName" defaultValue={student.packageName}><option>شهرية · 8 حصص</option><option>شهرية · 12 حصة</option></select></label><label className="field"><span>حالة الملف</span><select name="status" defaultValue={student.status}><option>نشط</option><option>موقوف</option></select></label></div>{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => navigate(-1)}>إلغاء</button><ProtectedButton permission="student.update" className="button primary">حفظ التعديلات</ProtectedButton></div></form></>
}

export function GroupDetailPage() {
  const { id } = useParams(), navigate = useNavigate()
  const role=useAppStore(state=>state.role),group = useAppStore(state => state.groups.find(item => item.id === id)), allStudents = useAppStore(state => state.students), update = useAppStore(state => state.updateGroup)
  const students = allStudents.filter(item => item.group === group?.name), [error, setError] = useState('')
  if (!group) return <EmptyState title="المجموعة غير موجودة" />
  const full = group.enrolled >= group.capacity
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('')
    const data = new FormData(event.currentTarget)
    const result = update(group.id, { name: String(data.get('name')), course: String(data.get('course')), instructor: String(data.get('instructor')), room: String(data.get('room')), schedule: String(data.get('schedule')), capacity: Number(data.get('capacity')), status: String(data.get('status')) as 'نشطة' | 'مكتملة' })
    if (!result.ok) { setError(result.message); return }
    navigate('/groups')
  }
  return <><PageHeader eyebrow={can(role,'group.assign')?'المجموعات / تعديل':'مجموعاتي / عرض'} title={group.name} description={`${group.enrolled} من ${group.capacity} طالب`} action={<Link className="button secondary" to="/groups">العودة للمجموعات</Link>} />{full && <div className="notice danger"><AlertTriangle /><strong>هذه المجموعة مكتملة السعة ولا تقبل إسناد طلاب جدد.</strong></div>}<div className="grid-two">{can(role,'group.assign')?<form className="panel" onSubmit={submit}><div className="form-grid"><label className="field full"><span>اسم المجموعة</span><input name="name" defaultValue={group.name} /></label><label className="field"><span>الدورة</span><input name="course" defaultValue={group.course} /></label><label className="field"><span>المدرس</span><input name="instructor" defaultValue={group.instructor} /></label><label className="field"><span>القاعة</span><input name="room" defaultValue={group.room} /></label><label className="field"><span>السعة</span><input name="capacity" type="number" min={group.enrolled} defaultValue={group.capacity} /></label><label className="field full"><span>الجدول</span><input name="schedule" defaultValue={group.schedule} /></label><label className="field"><span>الحالة</span><select name="status" defaultValue={full ? 'مكتملة' : group.status}><option>نشطة</option><option>مكتملة</option></select></label></div>{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><ProtectedButton permission="group.assign" className="button primary">حفظ المجموعة</ProtectedButton></div></form>:<section className="panel"><h3>بيانات مجموعتي</h3><div className="info-grid"><div><span>الدورة</span><strong>{group.course}</strong></div><div><span>القاعة</span><strong>{group.room}</strong></div><div><span>الجدول</span><strong>{group.schedule}</strong></div><div><span>الإشغال</span><strong>{group.enrolled} / {group.capacity}</strong></div></div></section>}<section className="panel"><h3><Users /> طلاب المجموعة</h3>{students.map(student => <Link className="list-row" to={`/students/${student.id}`} key={student.id}><div><strong>{student.name}</strong><small>{student.code}</small></div><StatusBadge tone={student.status === 'نشط' ? 'success' : 'neutral'}>{student.status}</StatusBadge></Link>)}{!students.length && <EmptyState title="لا توجد ملفات طلاب ظاهرة في هذه المجموعة" />}</section></div></>
}
