import { useMemo, useRef, useState, type ReactNode } from 'react'
import { Download, FileSpreadsheet, LoaderCircle, Printer } from 'lucide-react'
import { PageHeader, ProtectedButton, StatusBadge } from '../components/ui'
import { downloadWorkbook } from '../reporting/exportExcel'
import { buildReport, type ReportingRange } from '../reporting/selectors'
import { buildExecutiveSnapshot, ledgerConsistency } from '../reporting/executive'
import { useAppStore } from '../store/useAppStore'

type Preset='today'|'week'|'month'|'previous'|'custom'
const ranges:Record<Exclude<Preset,'custom'>,ReportingRange>={today:{from:'2026-08-11',to:'2026-08-11',label:'اليوم'},week:{from:'2026-08-08',to:'2026-08-13',label:'هذا الأسبوع'},month:{from:'2026-08-01',to:'2026-08-31',label:'هذا الشهر'},previous:{from:'2026-07-01',to:'2026-07-31',label:'الشهر السابق'}}
const money=(value:number)=>`${value.toLocaleString('ar-EG')} ج`

export function SystemSummaryPage(){
  const students=useAppStore(s=>s.students),teachers=useAppStore(s=>s.teachers),groups=useAppStore(s=>s.groups),sessions=useAppStore(s=>s.sessions),attendance=useAppStore(s=>s.attendance),payments=useAppStore(s=>s.payments),followups=useAppStore(s=>s.followups),audit=useAppStore(s=>s.audit),ledger=useAppStore(s=>s.ledger),executiveDecisions=useAppStore(s=>s.executiveDecisions),settings=useAppStore(s=>s.settings),role=useAppStore(s=>s.role),currentUserName=useAppStore(s=>s.currentUserName)
  const[preset,setPreset]=useState<Preset>('month'),[from,setFrom]=useState('2026-08-01'),[to,setTo]=useState('2026-08-31'),[group,setGroup]=useState(''),[pdfState,setPdfState]=useState<'idle'|'loading'|'error'|'success'>('idle')
  const reportRef=useRef<HTMLDivElement>(null)
  const range=preset==='custom'?{from,to,label:`من ${from} إلى ${to}`}:ranges[preset]
  const source=useMemo(()=>({students:group?students.filter(s=>s.group===group):students,teachers,groups:group?groups.filter(g=>g.name===group):groups,sessions:group?sessions.filter(s=>s.group===group):sessions,attendance:group?attendance.filter(s=>s.group===group):attendance,payments,followups,audit,ledger,executiveDecisions}),[students,teachers,groups,sessions,attendance,payments,followups,audit,ledger,executiveDecisions,group])
  const report=buildReport(source,range)
  const executive=buildExecutiveSnapshot(source,range),ledgerIssues=ledgerConsistency(source.students,ledger,payments)
  const exportExcel=()=>downloadWorkbook([
    {name:'الملخص التنفيذي',rows:[['NEXVORA — ملخص النظام','القيمة'],['الأكاديمية',settings.academyName],['فترة التقرير',range.label],['تم الإنشاء بواسطة',`${currentUserName} · ${role}`],...executive.kpis.map(k=>[k.label,k.value]),['استثناءات اتساق الدفتر',ledgerIssues.length]]},
    {name:'مقارنة الفترات',rows:[['المؤشر','الفترة الحالية','الفترة السابقة','التغير'],...executive.kpis.map(k=>[k.label,k.value,k.previous,k.change])]},
    {name:'المخاطر',rows:[['التصنيف','الخطورة','الخطر','السبب','القيمة المتأثرة','المسؤول','الحالة'],...executive.risks.map(r=>[r.category,r.severity,r.title,r.reason,r.value,r.owner,r.status])]},
    {name:'القرارات',rows:[['النوع','القرار','مقدم الطلب','التاريخ','الحالة','صاحب القرار','السبب'],...executiveDecisions.map(d=>[d.type,d.title,d.requestedByName,d.requestedAt,d.status,d.decidedByName||'',d.reason||''])]},
    {name:'دفتر الحركات',rows:[['المرجع','الطالب','النوع','المبلغ','التاريخ','المنشئ','المراجع','الرصيد قبل','الرصيد بعد'],...ledger.map(l=>[l.reference,source.students.find(s=>s.id===l.studentId)?.name||'—',l.type,l.amount,l.date,l.createdByName,l.reviewedByName||'',l.balanceBefore,l.balanceAfter])]},
    {name:'الطلاب',rows:[['كود الطالب','الاسم','الهاتف','المجموعة','حالة الملف','المدفوع','المتبقي','حالة السداد'],...source.students.map(s=>[s.code,s.name,s.phone,s.group||'غير مسند',s.status,s.paid,s.total-s.paid,s.due])]},
    {name:'المدرسون',rows:[['كود المدرس','اسم المدرس','الهاتف','التخصص','الحالة','عدد المجموعات','عدد الحصص في الفترة','القاعات المستخدمة'],...report.teachers.map(t=>[t.code,t.name,t.phone,t.specialty,t.status,t.groupCount,t.sessionCount,t.rooms.join('، ')])]},
    {name:'المجموعات',rows:[['المجموعة','المدرس','القاعة','السعة','عدد الطلاب','نسبة الإشغال','الحالة'],...source.groups.map(g=>[g.name,g.instructor,g.room,g.capacity,g.enrolled,g.capacity?Math.round(g.enrolled/g.capacity*100):0,g.status])]},
    {name:'الحصص',rows:[['التاريخ','اليوم','البداية','النهاية','المجموعة','المدرس','القاعة','الحالة','حالة الحضور'],...report.sessions.map(s=>[s.date,s.day,s.start,s.end,s.group,s.instructor,s.room,s.status,source.attendance.some(a=>a.sessionId===s.id)?'تم التسجيل':'لم يُسجّل'])]},
    {name:'الحضور',rows:[['التاريخ','الطالب','المجموعة','الحالة','سجله'],...report.attendance.map(a=>[a.date,source.students.find(s=>s.id===a.studentId)?.name||'—',a.group,a.status,a.recordedBy])]},
    {name:'المدفوعات',rows:[['الطالب','القيمة','الوسيلة','تاريخ التسجيل','الحالة','تاريخ المراجعة','المراجع'],...report.payments.map(p=>[source.students.find(s=>s.id===p.studentId)?.name||'—',p.amount,p.method,p.paymentDate,p.status,p.reviewedAt||'',p.reviewedBy||''])]},
    {name:'المتأخرات',rows:[['الطالب','المجموعة','المبلغ المتأخر','حالة الاستحقاق','آخر متابعة','التصعيد'],...report.overdue.map(s=>{const f=followups.filter(x=>x.studentId===s.id);return[s.name,s.group||'غير مسند',s.total-s.paid,s.due,f[0]?.result||'لم تبدأ',f.some(x=>x.escalated)?'مصعّدة':'غير مصعّدة']})]},
    {name:'النشاط',rows:[['الوقت','المستخدم','الدور','الإجراء','الكيان','قبل','بعد','السبب','الحساسية'],...audit.map(a=>[a.at,a.userName||a.user,a.user,a.title,a.entity||a.type,a.before||'',a.after||'',a.reason||a.detail,a.sensitivity||'عادية'])]},
  ],`NEXVORA-system-summary-${range.from}-${range.to}.xlsx`)
  const exportPdf=async()=>{
    if(!reportRef.current||pdfState==='loading')return
    setPdfState('loading');reportRef.current.classList.add('pdf-capture')
    try{
      const [{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')])
      await document.fonts.ready
      const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true})
      const pageWidth=210,pageHeight=297,margin=10,contentWidth=pageWidth-margin*2,contentHeight=pageHeight-margin*2-8
      const nodes=[...reportRef.current.querySelectorAll<HTMLElement>('.report-cover,.report-identity,.report-section')]
      let page=1,y=margin
      for(const node of nodes){
        const canvas=await html2canvas(node,{scale:1.7,backgroundColor:'#ffffff',useCORS:true,logging:false,windowWidth:1120})
        const imageHeight=canvas.height*contentWidth/canvas.width
        if(node.classList.contains('report-cover')){pdf.addImage(canvas.toDataURL('image/jpeg',.94),'JPEG',margin,margin,contentWidth,Math.min(imageHeight,contentHeight),undefined,'FAST');pdf.addPage();page+=1;y=margin;continue}
        if(y>margin&&y+imageHeight>margin+contentHeight){pdf.setFontSize(8);pdf.setTextColor(90);pdf.text(`${page}`,pageWidth/2,pageHeight-4,{align:'center'});pdf.addPage();page+=1;y=margin}
        if(imageHeight<=contentHeight){pdf.addImage(canvas.toDataURL('image/jpeg',.94),'JPEG',margin,y,contentWidth,imageHeight,undefined,'FAST');y+=imageHeight+4}else{
          const sliceHeight=Math.floor(canvas.width*contentHeight/contentWidth);let sourceY=0
          while(sourceY<canvas.height){const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=Math.min(sliceHeight,canvas.height-sourceY);slice.getContext('2d')?.drawImage(canvas,0,sourceY,canvas.width,slice.height,0,0,canvas.width,slice.height);const height=slice.height*contentWidth/slice.width;pdf.addImage(slice.toDataURL('image/jpeg',.94),'JPEG',margin,y,contentWidth,height,undefined,'FAST');sourceY+=slice.height;if(sourceY<canvas.height){pdf.setFontSize(8);pdf.setTextColor(90);pdf.text(`${page}`,pageWidth/2,pageHeight-4,{align:'center'});pdf.addPage();page+=1;y=margin}else y+=height+4}
        }
      }
      pdf.setFontSize(8);pdf.setTextColor(90);pdf.text(`${page}`,pageWidth/2,pageHeight-4,{align:'center'})
      pdf.save(`NEXVORA-system-summary-${range.from}-${range.to}.pdf`)
      setPdfState('success');window.setTimeout(()=>setPdfState('idle'),4000)
    }catch(error){console.error('PDF export failed',error);setPdfState('error')}finally{reportRef.current?.classList.remove('pdf-capture')}
  }
  return <div ref={reportRef} className="system-summary print-report"><div className="print-only report-cover"><strong>NEXVORA</strong><h1>ملخص النظام</h1><p>{settings.academyName} · {range.label}</p></div><PageHeader eyebrow="التقارير الإدارية" title="ملخص النظام" description="تقرير شامل عن الحالة التشغيلية والمالية للأكاديمية خلال الفترة المحددة." action={<div className="export-actions no-print"><ProtectedButton permission="report.export" className="button secondary" onClick={exportPdf} disabled={pdfState==='loading'}>{pdfState==='loading'?<LoaderCircle className="spinner"/>:<Download/>}{pdfState==='loading'?'جارٍ إنشاء PDF':'تنزيل PDF'}</ProtectedButton><ProtectedButton permission="report.export" className="button secondary" onClick={()=>window.print()}><Printer/>طباعة</ProtectedButton><ProtectedButton permission="report.export" className="button primary" onClick={exportExcel}><FileSpreadsheet/>تصدير Excel</ProtectedButton></div>}/>
  {pdfState==='success'&&<div className="notice success no-print" role="status" aria-live="polite">تم إنشاء ملف PDF وتنزيله بنجاح.</div>}{pdfState==='error'&&<div className="notice danger no-print" role="alert"><strong>تعذر إنشاء ملف PDF.</strong><p>أعد المحاولة، وإن استمرت المشكلة استخدم خيار الطباعة.</p><button className="button secondary" onClick={exportPdf}>إعادة المحاولة</button></div>}
  <section className="report-identity"><div><span>الأكاديمية</span><strong>{settings.academyName}</strong></div><div><span>فترة التقرير</span><strong>{range.label}</strong></div><div><span>تاريخ الإنشاء</span><strong>11 أغسطس 2026 · الآن</strong></div><div><span>أُنشئ بواسطة</span><strong>{currentUserName} · {role}</strong></div></section>
  <section className="filter-bar summary-filters no-print"><label>الفترة<select value={preset} onChange={e=>setPreset(e.target.value as Preset)}><option value="today">اليوم</option><option value="week">هذا الأسبوع</option><option value="month">هذا الشهر</option><option value="previous">الشهر السابق</option><option value="custom">نطاق مخصص</option></select></label>{preset==='custom'&&<><label>من<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}<label>المجموعة<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">كل المجموعات</option>{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></label></section>
  <ReportSection title="الملخص التنفيذي" description="أهم مؤشرات الحجم والتشغيل والمالية في الفترة المختارة."><div className="summary-kpis"><Kpi label="الطلاب" value={report.students.total}/><Kpi label="المدرسون النشطون" value={report.teacherMetrics.active}/><Kpi label="المجموعات" value={report.groups.total}/><Kpi label="الحصص" value={report.sessionMetrics.total}/><Kpi label="نسبة الحضور" value={report.attendanceMetrics.rate==null?'غير متاح':`${report.attendanceMetrics.rate}%`}/><Kpi label="التحصيل المعتمد" value={money(report.paymentMetrics.collected)}/><Kpi label="المبالغ المستحقة" value={money(report.finance.outstanding)}/><Kpi label="المبالغ المتأخرة" value={money(report.finance.overdue)}/></div></ReportSection>
  <ReportSection title="الصورة التنفيذية والمقارنة" description={`مقارنة مع الفترة السابقة ${executive.previous.from} إلى ${executive.previous.to}، مع عرض الاستثناءات والقرارات التي تحتاج تدخلًا.`}><div className="summary-kpis compact">{executive.kpis.map(k=><Kpi key={k.id} label={`${k.label} (${k.change})`} value={k.value}/>)}</div><div className="executive-report-grid"><div><h3>أهم الاستنتاجات</h3>{executive.insights.map((item,index)=><p key={index}>{index+1}. {item}</p>)}</div><div><h3>المخاطر المفتوحة</h3>{executive.risks.slice(0,5).map(r=><p key={r.id}><strong>{r.severity}:</strong> {r.title} · {r.value}</p>)}{!executive.risks.length&&<p>لا توجد مخاطر مفتوحة.</p>}</div></div><Table headers={['القرار','مقدم الطلب','الحالة','السبب']} rows={executiveDecisions.map(d=>[d.title,d.requestedByName,d.status,d.reason||'لم يُتخذ قرار'])}/>{ledgerIssues.length>0&&<div className="notice danger"><strong>استثناءات اتساق دفتر الحركات</strong><p>{ledgerIssues.join(' · ')}</p></div>}</ReportSection>
  <ReportSection title="الطلاب" description="حالة التسجيل والإسناد والسداد للطلاب الحاليين."><div className="summary-kpis compact"><Kpi label="إجمالي الطلاب" value={report.students.total}/><Kpi label="ملفات نشطة" value={report.students.active}/><Kpi label="غير مسندين إلى مجموعة" value={report.students.unassigned}/><Kpi label="حالات سداد متأخرة" value={report.finance.overdueStudents}/></div><Table headers={['الطالب','المجموعة','حالة الملف','المدفوع','المتبقي']} rows={source.students.map(s=>[s.name,s.group||'غير مسند',s.status,money(s.paid),money(s.total-s.paid)])}/></ReportSection>
  <ReportSection title="المدرسون" description="الإسناد التشغيلي وحجم الحصص لكل مدرس خلال الفترة."><div className="summary-kpis compact"><Kpi label="المدرسون النشطون" value={report.teacherMetrics.active}/><Kpi label="لديهم حصص في الفترة" value={report.teacherMetrics.working}/><Kpi label="بلا مجموعات" value={report.teacherMetrics.withoutGroups}/><Kpi label="بلا حصص قادمة" value={report.teacherMetrics.withoutUpcoming}/></div><Table headers={['المدرس','التخصص','المجموعات','الحصص','القاعات','الحالة']} rows={report.teachers.map(t=>[t.name,t.specialty,t.groupCount,t.sessionCount,t.rooms.join('، ')||'—',t.status])}/></ReportSection>
  <ReportSection title="المجموعات وإشغالها" description="توزيع الطلاب والطاقة الاستيعابية للمجموعات."><div className="summary-kpis compact"><Kpi label="متوسط الإشغال" value={report.groups.occupancy==null?'غير متاح':`${report.groups.occupancy}%`}/><Kpi label="مكتملة" value={report.groups.full}/><Kpi label="قريبة من الاكتمال" value={report.groups.near}/></div><Table headers={['المجموعة','المدرس','القاعة','الإشغال','النسبة','الحالة']} rows={source.groups.map(g=>[g.name,g.instructor,g.room,`${g.enrolled}/${g.capacity}`,`${g.capacity?Math.round(g.enrolled/g.capacity*100):0}%`,g.status])}/></ReportSection>
  <ReportSection title="الحصص والجدولة" description="الحصص الواقعة داخل الفترة المحددة وحالة تسجيل حضورها."><div className="summary-kpis compact"><Kpi label="إجمالي الحصص" value={report.sessionMetrics.total}/><Kpi label="مكتملة" value={report.sessionMetrics.completed}/><Kpi label="قادمة" value={report.sessionMetrics.upcoming}/><Kpi label="ينقصها حضور" value={report.sessionMetrics.attendanceMissing}/></div><Table headers={['التاريخ','الوقت','المجموعة','المدرس','القاعة','الحالة','الحضور']} rows={report.sessions.map(s=>[s.date,s.start,s.group,s.instructor,s.room,s.status,source.attendance.some(a=>a.sessionId===s.id)?'تم التسجيل':'لم يُسجّل'])}/></ReportSection>
  <ReportSection title="الحضور" description="حساب النسبة مبني على سجلات الطلاب: الحاضر والمتأخر ضمن المشاركة."><div className="summary-kpis compact"><Kpi label="السجلات" value={report.attendanceMetrics.records}/><Kpi label="حاضر" value={report.attendanceMetrics.present}/><Kpi label="متأخر" value={report.attendanceMetrics.late}/><Kpi label="غائب" value={report.attendanceMetrics.absent}/><Kpi label="بعذر" value={report.attendanceMetrics.excused}/></div></ReportSection>
  <ReportSection title="المدفوعات والمبالغ المستحقة" description="المبالغ المحصلة تشمل الدفعات المعتمدة فقط؛ المعلّقة والمرفوضة لا تدخل في التحصيل."><div className="summary-kpis compact"><Kpi label="دفعات مسجلة" value={report.paymentMetrics.submitted}/><Kpi label="تنتظر المراجعة" value={report.paymentMetrics.pending}/><Kpi label="معتمدة" value={report.paymentMetrics.approved}/><Kpi label="مرفوضة" value={report.paymentMetrics.rejected}/><Kpi label="إجمالي المستحق" value={money(report.finance.outstanding)}/><Kpi label="إجمالي المتأخر" value={money(report.finance.overdue)}/></div><Table headers={['الطالب','المبلغ','الطريقة','التاريخ','الحالة','المراجع']} rows={report.payments.map(p=>[source.students.find(s=>s.id===p.studentId)?.name||'—',money(p.amount),p.method,p.paymentDate,p.status,p.reviewedBy||'لم تُراجع'])}/></ReportSection>
  <ReportSection title="المتابعات والحالات التي تحتاج مراجعة" description="ملخص أعمال المتابعة والتصعيد المسجلة في الفترة."><div className="summary-kpis compact"><Kpi label="المتابعات" value={report.followupMetrics.total}/><Kpi label="الحالات المصعّدة" value={report.finance.escalated}/><Kpi label="دفعات معلقة" value={report.paymentMetrics.pending}/><Kpi label="حصص بلا حضور" value={report.sessionMetrics.attendanceMissing}/></div></ReportSection>
  <ReportSection title="النشاط والتغييرات" description="آخر العمليات المهمة مع هوية المستخدم والأثر وسبب القرار."><div className="audit-summary">{audit.slice(0,10).map(a=><article key={a.id}><StatusBadge tone={a.sensitivity==='حرجة'?'danger':a.sensitivity==='مهمة'?'warning':'neutral'}>{a.sensitivity||a.type}</StatusBadge><div><strong>{a.title}</strong><p>{a.detail}</p>{(a.before||a.after)&&<p>قبل: {a.before||'—'} · بعد: {a.after||'—'}</p>}<small>{a.userName||a.user} · {a.user} · {a.at}{a.reason?` · السبب: ${a.reason}`:''}</small></div></article>)}</div></ReportSection>
  <footer className="print-only report-footer">NEXVORA · ملخص النظام · {range.label}</footer></div>
}

function ReportSection({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="report-section panel"><header><h2>{title}</h2><p>{description}</p></header>{children}</section>}
function Kpi({label,value}:{label:string;value:string|number}){return <div className="summary-kpi"><span>{label}</span><strong>{value}</strong></div>}
function Table({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="table-wrap responsive-table summary-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td data-label={headers[j]} key={j}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty-inline">لا توجد بيانات مطابقة للفترة المحددة.</p>}</div>}
