import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { AlertCircle, Building2, KeyRound, LoaderCircle, Save, ShieldCheck, UserCog } from 'lucide-react'
import type { DemoState, Role } from '../domain/types'
import { PageHeader } from '../components/ui'
import { can } from '../domain/permissions'
import { useAppStore } from '../store/useAppStore'

export function LoginPage(){const login=useAppStore(state=>state.login),allTeachers=useAppStore(state=>state.teachers),teachers=allTeachers.filter(item=>item.status==='نشط');const [role,setRole]=useState<Role>('مدير التشغيل'),[teacherId,setTeacherId]=useState(teachers[0]?.id||''),[email,setEmail]=useState('demo@nexvora.academy');const submit=(event:FormEvent)=>{event.preventDefault();login(role,role==='المدرس'?teacherId:undefined);window.location.hash='#/'};return <main className="login-page"><section className="login-card"><div className="login-brand"><span>N</span><div><strong>NEXVORA</strong><small>إدارة الأكاديمية</small></div></div><p className="eyebrow">تجربة النموذج المنظم</p><h1>تسجيل الدخول</h1><p>كل حساب يفتح مساحة العمل والبيانات المصرح بها فقط.</p><form onSubmit={submit}><label className="field"><span>البريد الإلكتروني</span><input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label className="field"><span>الدور التجريبي</span><select value={role} onChange={event=>setRole(event.target.value as Role)}>{(['مدير التشغيل','موظف المتابعة','المدرس','المحاسب'] as Role[]).map(item=><option key={item}>{item}</option>)}</select></label>{role==='المدرس'&&<label className="field"><span>حساب المدرس</span><select value={teacherId} onChange={event=>setTeacherId(event.target.value)}>{teachers.map(item=><option key={item.id} value={item.id}>{item.name} · {item.specialty}</option>)}</select><small>سيظهر لهذا الحساب طلابه ومجموعاته وحصصه فقط.</small></label>}<button className="button primary" type="submit"><KeyRound/>دخول إلى مساحة العمل</button></form><div className="login-note"><ShieldCheck/><span>هذه تجربة محلية؛ لا تُرسل بيانات الدخول إلى أي خادم.</span></div></section></main>}

export function SettingsPage(){const settings=useAppStore(state=>state.settings),save=useAppStore(state=>state.saveSettings),role=useAppStore(state=>state.role),teacher=useAppStore(state=>state.teachers.find(item=>item.id===state.currentTeacherId)),logout=useAppStore(state=>state.logout),canEditAcademy=can(role,'settings.academy');const [draft,setDraft]=useState(settings),[saved,setSaved]=useState(false);const submit=(event:FormEvent)=>{event.preventDefault();save(canEditAcademy?draft:{...settings,theme:draft.theme,density:draft.density});setSaved(true)};return <><PageHeader eyebrow="الإعدادات" title="الحساب والمظهر" description="إعدادات حسابك ومظهر مساحة العمل المخصصة لدورك."/><div className="settings-layout"><aside className="panel account-summary"><div className="avatar">{teacher?.name[0]||role[0]}</div><h3>{teacher?.name||role}</h3><p>{teacher?.email||settings.email}</p><dl><div><dt>الدور</dt><dd>{role}</dd></div><div><dt>الأكاديمية</dt><dd>{settings.academyName}</dd></div><div><dt>نطاق الوصول</dt><dd>{role==='مدير التشغيل'?'كل النظام':role==='المدرس'?'بياناتك التعليمية فقط':'مهام الدور فقط'}</dd></div></dl><button className="button danger" onClick={logout}>تسجيل الخروج</button></aside><form className="panel" onSubmit={submit}>{canEditAcademy&&<div className="settings-section"><h3><Building2/>بيانات الأكاديمية</h3><div className="form-grid"><label className="field full"><span>اسم الأكاديمية</span><input value={draft.academyName} onChange={event=>setDraft({...draft,academyName:event.target.value})}/></label><label className="field"><span>البريد</span><input type="email" value={draft.email} onChange={event=>setDraft({...draft,email:event.target.value})}/></label><label className="field"><span>الهاتف</span><input value={draft.phone} onChange={event=>setDraft({...draft,phone:event.target.value})}/></label></div></div>}<div className="settings-section"><h3><UserCog/>المظهر والوصول</h3><p className="notice neutral">الدور والصلاحيات يحددهما حساب الدخول ولا يمكن رفعهما من الإعدادات.</p><div className="choice-row"><label><input type="radio" checked={draft.theme==='light'} onChange={()=>setDraft({...draft,theme:'light'})}/>مظهر فاتح</label><label><input type="radio" checked={draft.theme==='dark'} onChange={()=>setDraft({...draft,theme:'dark'})}/>مظهر داكن</label></div><div className="choice-row"><label><input type="radio" checked={draft.density==='comfortable'} onChange={()=>setDraft({...draft,density:'comfortable'})}/>مريح</label><label><input type="radio" checked={draft.density==='compact'} onChange={()=>setDraft({...draft,density:'compact'})}/>مضغوط</label></div></div>{saved&&<p className="notice success" role="status">تم حفظ الإعدادات محليًا.</p>}<div className="form-actions"><button className="button primary"><Save/>حفظ الإعدادات</button></div></form></div></>}

export function DemoStateBoundary({children}:{children:ReactNode}){const demoState=useAppStore(state=>state.demoState);if(demoState==='loading')return <section className="state-view" role="status"><LoaderCircle className="spinner"/><h2>جارٍ تحميل البيانات</h2><div className="skeleton-grid">{[1,2,3,4].map(item=><i key={item}/>)}</div></section>;if(demoState==='empty')return <section className="state-view"><Building2/><h2>لا توجد بيانات في هذا العرض</h2><p>هذه حالة فارغة لاختبار الرسائل والإجراءات عندما تبدأ الأكاديمية من الصفر.</p></section>;if(demoState==='error')return <section className="state-view error-state" role="alert"><AlertCircle/><h2>تعذر تحميل البيانات</h2><p>حالة تجريبية لاختبار ظهور الخطأ واستعادة الاستخدام.</p></section>;return children}

export function DemoStateSwitcher(){const state=useAppStore(item=>item.demoState),set=useAppStore(item=>item.setDemoState);useEffect(()=>{if(state!=='loading')return;const timer=setTimeout(()=>set('populated'),900);return()=>clearTimeout(timer)},[state,set]);return <label className="demo-switcher"><span>حالة العرض</span><select value={state} onChange={event=>set(event.target.value as DemoState)}><option value="populated">بيانات مكتملة</option><option value="loading">تحميل</option><option value="empty">فارغة</option><option value="error">خطأ</option></select></label>}
