import { useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, CalendarDays, Clock3, Plus, UsersRound } from 'lucide-react'
import { EmptyState, Metric, PageHeader, ProtectedButton, StatusBadge } from '../components/ui'
import type { ScheduleConflict, TeacherAvailability } from '../domain/types'
import { conflictMessage } from '../domain/validation'
import { useAppStore } from '../store/useAppStore'
import { RecordActions } from './StudentsPage'

const days=['السبت','الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس']
const starts=['10:00 ص','11:00 ص','12:00 م','1:00 م','2:00 م','3:00 م','4:00 م','5:00 م','6:00 م','7:00 م','8:00 م']
const ends=['11:00 ص','12:00 م','1:00 م','2:00 م','3:00 م','4:00 م','5:00 م','6:00 م','7:00 م','8:00 م','9:00 م']

export function TeachersPage(){
  const teachers=useAppStore(s=>s.teachers),groups=useAppStore(s=>s.groups),sessions=useAppStore(s=>s.sessions)
  const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[assignment,setAssignment]=useState('')
  const rows=teachers.filter(teacher=>{const teacherGroups=groups.filter(g=>g.instructor===teacher.name),hasAssignment=teacherGroups.length>0;return(!query||`${teacher.name} ${teacher.phone} ${teacher.code} ${teacher.specialty}`.includes(query))&&(!status||teacher.status===status)&&(!assignment||(assignment==='assigned'?hasAssignment:!hasAssignment))})
  return <><PageHeader eyebrow="إدارة هيئة التدريس" title="المدرسون" description="إدارة بيانات المدرسين وتوفرهم والمجموعات والحصص المسندة إليهم." action={<Link className="button primary" to="/teachers/new"><Plus/>إضافة مدرس</Link>}/>
  <section className="metrics"><Metric label="المدرسون النشطون" value={teachers.filter(t=>t.status==='نشط').length} hint="متاحون للإسناد"/><Metric label="يعملون اليوم" value={new Set(sessions.filter(s=>s.date==='2026-08-11').map(s=>s.instructor)).size} hint="لديهم حصص اليوم"/><Metric label="بلا مجموعات" value={teachers.filter(t=>t.status==='نشط'&&!groups.some(g=>g.instructor===t.name)).length} hint="يحتاجون مراجعة الإسناد"/><Metric label="الحصص القادمة" value={sessions.filter(s=>s.date>='2026-08-11'&&s.status!=='ملغاة').length} hint="حسب الجدول الحالي"/></section>
  <section className="panel"><div className="filter-bar"><label>بحث<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="الاسم أو الهاتف أو الكود"/></label><label>الحالة<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option><option>نشط</option><option>غير نشط</option></select></label><label>الإسناد<select value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="">الكل</option><option value="assigned">مسند إلى مجموعة</option><option value="unassigned">بلا مجموعة</option></select></label></div>
  <div className="table-wrap responsive-table"><table><thead><tr><th>المدرس</th><th>التخصص</th><th>المجموعات</th><th>الحصص القادمة</th><th>أقرب حصة</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{rows.map(teacher=>{const teacherGroups=groups.filter(g=>g.instructor===teacher.name),upcoming=sessions.filter(s=>s.instructor===teacher.name&&s.date>='2026-08-11'&&s.status!=='ملغاة').sort((a,b)=>a.date.localeCompare(b.date)),warning=!teacherGroups.length?'لا توجد مجموعات مسندة.':!upcoming.length?'لا توجد حصص قادمة.':'';return <tr key={teacher.id}><td data-label="المدرس"><strong>{teacher.name}</strong><small>{teacher.code} · {teacher.phone}</small>{warning&&<span className="inline-warning"><AlertTriangle/> {warning}</span>}</td><td data-label="التخصص">{teacher.specialty||'غير محدد'}</td><td data-label="المجموعات">{teacherGroups.length}</td><td data-label="الحصص القادمة">{upcoming.length}</td><td data-label="أقرب حصة">{upcoming[0]?`${upcoming[0].date} · ${upcoming[0].start}`:'—'}</td><td data-label="الحالة"><StatusBadge tone={teacher.status==='نشط'?'success':'neutral'}>{teacher.status}</StatusBadge></td><td data-label="الإجراء"><Link className="text-link" to={`/teachers/${teacher.id}`}>عرض الملف</Link></td></tr>})}</tbody></table></div>{!rows.length&&<EmptyState title="لم يتم العثور على مدرسين مطابقين لبحثك."/>}</section></>
}

export function NewTeacherPage(){const add=useAppStore(s=>s.addTeacher),teachers=useAppStore(s=>s.teachers),navigate=useNavigate();const[error,setError]=useState(''),[duplicateId,setDuplicateId]=useState('');const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),result=add({name:String(d.get('name')),phone:String(d.get('phone')),email:String(d.get('email')||''),specialty:String(d.get('specialty')),status:'نشط',startDate:String(d.get('startDate')),notes:String(d.get('notes')||''),availability:[]});if(!result.ok){setError(result.message);setDuplicateId(String(result.meta?.teacherId||''));return}navigate(`/teachers/${result.value.id}`)};return <><PageHeader eyebrow="المدرسون / إضافة" title="إضافة مدرس" description="أنشئ الملف الأساسي أولًا، ثم أضف أوقات التوفر والمجموعات من ملف المدرس."/><form className="flow-card" onSubmit={submit}><div className="form-grid"><label className="field full"><span>الاسم الكامل</span><input name="name" required/></label><label className="field"><span>رقم الهاتف</span><input name="phone" inputMode="tel" required/></label><label className="field"><span>البريد الإلكتروني</span><input name="email" type="email"/></label><label className="field"><span>التخصص أو الدورة</span><input name="specialty" required/></label><label className="field"><span>تاريخ بدء العمل</span><input name="startDate" type="date" defaultValue="2026-08-11"/></label><label className="field full"><span>ملاحظات</span><textarea name="notes"/></label></div>{error&&<div className="duplicate-warning" role="alert"><AlertTriangle/><div><strong>{error}</strong>{duplicateId&&<Link className="text-link" to={`/teachers/${duplicateId}`}>فتح ملف {teachers.find(t=>t.id===duplicateId)?.name}</Link>}</div></div>}<div className="form-actions"><Link className="button secondary" to="/teachers">إلغاء</Link><ProtectedButton permission="teacher.create" className="button primary">حفظ وفتح الملف</ProtectedButton></div></form></>}

type TeacherTab='overview'|'availability'|'schedule'|'groups'|'sessions'|'activity'
export function TeacherProfilePage(){const{id}=useParams(),teacher=useAppStore(s=>s.teachers.find(t=>t.id===id)),groups=useAppStore(s=>s.groups),sessions=useAppStore(s=>s.sessions),audit=useAppStore(s=>s.audit),saveAvailability=useAppStore(s=>s.saveTeacherAvailability),assign=useAppStore(s=>s.assignTeacherToGroup);const[tab,setTab]=useState<TeacherTab>('overview'),[availability,setAvailability]=useState<TeacherAvailability[]>(teacher?.availability||[]),[error,setError]=useState(''),[saved,setSaved]=useState(false),[groupId,setGroupId]=useState('');if(!teacher)return <EmptyState title="ملف المدرس غير موجود"/>;const teacherGroups=groups.filter(g=>g.instructor===teacher.name),teacherSessions=sessions.filter(s=>s.instructor===teacher.name).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`)),upcoming=teacherSessions.filter(s=>s.date>='2026-08-11'&&s.status!=='ملغاة'),rooms=[...new Set(teacherSessions.map(s=>s.room))];const save=()=>{const result=saveAvailability(teacher.id,availability);if(!result.ok){setError(result.message);return}setError('');setSaved(true)};const assignGroup=()=>{const result=assign(teacher.id,groupId);if(!result.ok){setError(result.message);return}setError('');setSaved(true);setGroupId('')};const tabs:[TeacherTab,string][]=[['overview','نظرة عامة'],['availability','أوقات التوفر'],['schedule','الجدول'],['groups','المجموعات'],['sessions','الحصص'],['activity','سجل النشاط']];return <><PageHeader eyebrow={`المدرسون / ${teacher.code}`} title={teacher.name} description={`${teacher.specialty} · ${teacher.phone}`} action={<div className="page-actions"><Link className="button secondary" to={`/teachers/${teacher.id}/edit`}>تعديل البيانات</Link><Link className="button primary" to={`/teachers/${teacher.id}/sessions/new`}>إضافة حصة</Link></div>}/><section className="teacher-hero panel"><div className="avatar teacher-avatar">{teacher.name[0]}</div><div><h3>{teacher.name}</h3><p>{teacher.specialty} · بدأ في {teacher.startDate||'تاريخ غير محدد'}</p></div><StatusBadge tone={teacher.status==='نشط'?'success':'neutral'}>{teacher.status}</StatusBadge></section><nav className="tabs teacher-tabs" aria-label="أقسام ملف المدرس">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>{error&&<p className="field-error" role="alert">{error}</p>}{saved&&<p className="notice success" role="status">تم حفظ التغيير وتحديث الشاشات المرتبطة.</p>}
  {tab==='overview'&&<><section className="metrics"><Metric label="المجموعات المسندة" value={teacherGroups.length}/><Metric label="الحصص القادمة" value={upcoming.length}/><Metric label="أقرب حصة" value={upcoming[0]?.start||'لا توجد'} hint={upcoming[0]?.date}/><Metric label="القاعات المستخدمة" value={rooms.length} hint={rooms.join('، ')||'لا توجد'}/></section>{(!teacherGroups.length||!upcoming.length)&&<section className="notice warning"><AlertTriangle/><strong>{!teacherGroups.length?'لا توجد مجموعات مسندة إلى هذا المدرس.':'لا توجد حصص قادمة لهذا المدرس.'}</strong></section>}<section className="panel"><h3>البيانات الأساسية</h3><dl className="info-grid"><div><dt>الكود</dt><dd>{teacher.code}</dd></div><div><dt>الهاتف</dt><dd>{teacher.phone}</dd></div><div><dt>البريد</dt><dd>{teacher.email||'غير مسجل'}</dd></div><div><dt>الملاحظات</dt><dd>{teacher.notes||'لا توجد'}</dd></div></dl></section></>}
  {tab==='availability'&&<section className="panel"><div className="section-title"><div><h3>أوقات توفر المدرس</h3><p>التوفر يحدد الأوقات المسموح بالجدولة داخلها، ولا ينشئ حصصًا.</p></div><button className="button secondary" onClick={()=>setAvailability(v=>[...v,{id:`av-${Date.now()}`,day:'السبت',start:'4:00 م',end:'5:00 م'}])}><Plus/>إضافة فترة</button></div><div className="availability-list">{availability.map(block=><div className="availability-row" key={block.id}><select aria-label="اليوم" value={block.day} onChange={e=>setAvailability(v=>v.map(x=>x.id===block.id?{...x,day:e.target.value}:x))}>{days.map(d=><option key={d}>{d}</option>)}</select><select aria-label="البداية" value={block.start} onChange={e=>setAvailability(v=>v.map(x=>x.id===block.id?{...x,start:e.target.value}:x))}>{starts.map(t=><option key={t}>{t}</option>)}</select><select aria-label="النهاية" value={block.end} onChange={e=>setAvailability(v=>v.map(x=>x.id===block.id?{...x,end:e.target.value}:x))}>{ends.map(t=><option key={t}>{t}</option>)}</select><button className="button danger subtle" onClick={()=>setAvailability(v=>v.filter(x=>x.id!==block.id))}>حذف</button></div>)}{!availability.length&&<EmptyState title="لم تُحدد أوقات توفر بعد" description="يمكن جدولة المدرس دون قيد حتى تضيف فترات توفر."/>}</div><div className="form-actions"><ProtectedButton permission="teacher.schedule" className="button primary" onClick={save}>حفظ أوقات التوفر</ProtectedButton></div></section>}
  {tab==='schedule'&&<section className="panel"><h3>جدول المدرس الأسبوعي</h3><div className="teacher-week">{days.map(day=><article key={day}><strong>{day}</strong>{teacherSessions.filter(s=>s.day===day).map(s=><Link key={s.id} to={`/sessions/${s.id}`}><b>{s.start}–{s.end}</b><span>{s.group}</span><small>{s.room}</small></Link>)}{!teacherSessions.some(s=>s.day===day)&&<small>لا توجد حصص</small>}</article>)}</div></section>}
  {tab==='groups'&&<section className="panel"><div className="section-title"><h3>المجموعات المسندة</h3><div className="inline-action"><select aria-label="اختر مجموعة" value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">اختر مجموعة</option>{groups.filter(g=>g.instructor!==teacher.name).map(g=><option value={g.id} key={g.id}>{g.name} · {g.schedule}</option>)}</select><ProtectedButton permission="teacher.assign" disabled={!groupId} className="button primary" onClick={assignGroup}>إسناد مجموعة</ProtectedButton></div></div>{teacherGroups.map(g=><Link className="list-row" key={g.id} to={`/groups/${g.id}`}><span className="row-icon"><UsersRound/></span><div><strong>{g.name}</strong><small>{g.schedule} · {g.room}</small></div><b>{g.enrolled}/{g.capacity}</b></Link>)}{!teacherGroups.length&&<EmptyState title="لا توجد مجموعات مسندة"/>}</section>}
  {(tab==='sessions'||tab==='schedule')&&tab==='sessions'&&<section className="panel"><h3>كل حصص المدرس</h3>{teacherSessions.map(s=><Link className="list-row" to={`/sessions/${s.id}`} key={s.id}><span className="row-icon"><CalendarDays/></span><div><strong>{s.group}</strong><small>{s.date} · {s.room}</small></div><b>{s.start}</b><StatusBadge tone={s.status==='مكتملة'?'success':'neutral'}>{s.status}</StatusBadge></Link>)}{!teacherSessions.length&&<EmptyState title="لا توجد حصص مسندة"/>}</section>}
  {tab==='activity'&&<section className="panel"><h3>سجل النشاط المرتبط</h3>{audit.filter(a=>a.entityId===teacher.id||a.detail.includes(teacher.name)).map(a=><article className="timeline-item" key={a.id}><strong>{a.title}</strong><p>{a.detail}</p><small>{a.user} · {a.at}</small></article>)}{!audit.some(a=>a.entityId===teacher.id||a.detail.includes(teacher.name))&&<EmptyState title="لا توجد عمليات مسجلة لهذا المدرس"/>}</section>}</>}

export function EditTeacherPage(){
  const{id}=useParams(),teacher=useAppStore(s=>s.teachers.find(t=>t.id===id)),update=useAppStore(s=>s.updateTeacher),archiveTeacher=useAppStore(s=>s.archiveTeacher),deleteTeacher=useAppStore(s=>s.deleteTeacher),navigate=useNavigate()
  const[error,setError]=useState('')
  if(!teacher)return <EmptyState title="ملف المدرس غير موجود"/>
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),result=update(teacher.id,{name:String(d.get('name')),phone:String(d.get('phone')),email:String(d.get('email')),specialty:String(d.get('specialty')),status:String(d.get('status')) as 'نشط'|'غير نشط'|'مؤرشف',notes:String(d.get('notes'))});if(!result.ok){setError(result.message);return}navigate(`/teachers/${teacher.id}`)}
  return <><PageHeader eyebrow="ملف المدرس / تعديل" title="تعديل بيانات المدرس" description="يُحفظ التاريخ السابق، ويُمنع إيقاف مدرس لديه حصص قادمة."/><form className="flow-card" onSubmit={submit}><div className="form-grid"><label className="field full"><span>الاسم</span><input name="name" defaultValue={teacher.name} required/></label><label className="field"><span>الهاتف</span><input name="phone" defaultValue={teacher.phone} required/></label><label className="field"><span>البريد</span><input name="email" type="email" defaultValue={teacher.email}/></label><label className="field"><span>التخصص</span><input name="specialty" defaultValue={teacher.specialty}/></label><label className="field"><span>الحالة</span><select name="status" defaultValue={teacher.status}><option>نشط</option><option>غير نشط</option><option>مؤرشف</option></select></label><label className="field full"><span>ملاحظات</span><textarea name="notes" defaultValue={teacher.notes}/></label></div>{error&&<p className="field-error" role="alert">{error}</p>}<div className="form-actions"><Link className="button secondary" to={`/teachers/${teacher.id}`}>إلغاء</Link><ProtectedButton permission="teacher.update" className="button primary">حفظ التعديلات</ProtectedButton></div></form><section className="panel danger-zone"><h3>إدارة دورة حياة الملف</h3><p>الأرشفة قابلة للاستعادة، أما الحذف النهائي فيُمنع تلقائيًا عند وجود مجموعات أو حصص مرتبطة.</p><RecordActions name={`المدرس ${teacher.name}`} archived={teacher.status==='مؤرشف'} onArchive={value=>archiveTeacher(teacher.id,value)} onDelete={()=>deleteTeacher(teacher.id)} deleteImpact="يجب إعادة إسناد كل المجموعات والحصص المرتبطة قبل السماح بالحذف النهائي." onDeleted={()=>navigate('/teachers')}/></section></>
}

export function NewTeacherSessionPage(){const{id}=useParams(),teacher=useAppStore(s=>s.teachers.find(t=>t.id===id)),groups=useAppStore(s=>s.groups),add=useAppStore(s=>s.addSession),navigate=useNavigate();const[error,setError]=useState(''),[conflicts,setConflicts]=useState<ScheduleConflict[]>([]);if(!teacher)return <EmptyState title="ملف المدرس غير موجود"/>;const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setConflicts([]);const d=new FormData(e.currentTarget),date=String(d.get('date')),day=new Intl.DateTimeFormat('ar-EG',{weekday:'long'}).format(new Date(`${date}T12:00:00`));const result=add({group:String(d.get('group')),instructor:teacher.name,room:String(d.get('room')),date,day,start:String(d.get('start')),end:String(d.get('end'))});if(!result.ok){const found=result.meta?.conflicts as ScheduleConflict[]|undefined;if(found)setConflicts(found);else setError(result.message);return}navigate(`/sessions/${result.value.id}`)};return <><PageHeader eyebrow={`المدرسون / ${teacher.name}`} title="إضافة حصة" description="سيتم فحص توفر المدرس وتعارض المدرس والمجموعة والقاعة قبل الحفظ."/><form className="flow-card" onSubmit={submit}>{error&&<p className="field-error" role="alert">{error}</p>}{conflicts.length>0&&<div className="conflict-list" role="alert">{conflicts.map((c,i)=><article key={i}><StatusBadge tone="danger">تعارض</StatusBadge><p>{conflictMessage(c)}</p></article>)}</div>}<div className="form-grid"><label className="field"><span>المدرس</span><input value={teacher.name} disabled/></label><label className="field"><span>المجموعة</span><select name="group">{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></label><label className="field"><span>التاريخ</span><input name="date" type="date" defaultValue="2026-08-12" required/></label><label className="field"><span>القاعة</span><select name="room">{['قاعة 1','قاعة 2','قاعة 3','قاعة 4','قاعة 5'].map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>وقت البداية</span><select name="start">{starts.slice(6).map(t=><option key={t}>{t}</option>)}</select></label><label className="field"><span>وقت النهاية</span><select name="end">{ends.slice(6).map(t=><option key={t}>{t}</option>)}</select></label></div><div className="form-actions"><Link className="button secondary" to={`/teachers/${teacher.id}`}>إلغاء</Link><ProtectedButton permission="teacher.schedule" className="button primary"><Clock3/>فحص وحفظ الحصة</ProtectedButton></div></form></>}
